package net.mike.bot.event;

public enum Event {
	
	// Define all events here.
	
	UPDATE_ENTITIES,
	DRAW_ENTITIES,
	
	ENTITY_BOT_CREATED,
	
	ENTITY_FOOD_SPECK_DESTROYED,
	
	KEYBOARD_UP_PRESSED,
	KEYBOARD_UP_RELEASED,
	KEYBOARD_DOWN_PRESSED,
	KEYBOARD_DOWN_RELEASED,
	KEYBOARD_LEFT_PRESSED,
	KEYBOARD_LEFT_RELEASED,
	KEYBOARD_RIGHT_PRESSED,
	KEYBOARD_RIGHT_RELEASED,

}
